name: Data Pipeline 
on:
  workflow_dispatch: # Isso cria o botão manual
    inputs:
      log_level:
        description: 'Nível de log'
        required: false
        default: 'info'
  push:
    branches:
      - main
      - master
    paths:
      - 'backend/downloads/*.csv'

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: |
          cd backend
          npm install

      - name: 1. Executar Extração dos CSVs
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd backend
          npm run extract

      - name: 2. Atualizar Ícones dos Campeões
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd backend
          node src/services/updateChampionIcons.js
